backend:
  image: node:latest
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: 'sqoop_database_test'
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
    POSTGRES_HOST_AUTH_METHOD: trust
  connect:
    image: postgres
    script:
      - export PGPASSWORD=$POSTGRES_PASSWORD
      - psql -h "postgres" -U "$POSTGRES_USER" -d "$POSTGRES_DB" -c "SELECT 'OK' AS status;"
  cache:
    paths:
      - backend/node_modules/
  before_script:
    - cd backend
    - DATABSE_URL_TEST=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    - npm install
    - npm run migrate:test
  script:
    - npm run test

frontend:
  image: node:latest
  cache:
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm install
    - npm run generate
  script:
    - npm run test
