backend:
  image: node:latest
  services:
    - postgres:latest
  cache:
    paths:
      - backend/node_modules/
  before_script:
    - cd backend
    - npm install
    - npm run migrate:test
  script:
    - npm run test

frontend:
  image: node:latest
  cache:
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm install
    - npm run generate
  script:
    - npm run test
