backend:
  image: node:latest
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: 'postgres'
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: ''
    POSTGRES_HOST_AUTH_METHOD: trust
  cache:
    paths:
      - backend/node_modules/
  before_script:
    - cd backend
    - npm install
    - npm run generate
    - npm run migrate:test
  script:
    - npm run test

frontend:
  image: node:latest
  cache:
    paths:
      - frontend/node_modules/
  before_script:
    - cd frontend
    - npm install
    - npx graphql-codegen
  script:
    - npm run test
