const accountSources = [
  { label: 'All Accounts', username: '' },
  { label: 'ABS-CBN News', username: 'ABSCBNNews' },
  { label: 'CNN Philippines', username: 'cnnphilippines' },
  { label: 'GMA News', username: 'gmanews' },
  { label: 'Rappler', username: 'rapplerdotcom' },
  { label: 'Inquirer', username: 'inquirerdotnet' },
  { label: 'Manila Bulettin News', username: 'manilabulletin' },
  { label: 'Phil News Agency', username: 'pnagovph' },
  { label: 'Senate of the Philippines', username: 'senatePH' },
  {
    label: 'House of Representatives of the Philippines',
    username: 'HouseofRepsPH',
  },
  {
    label: 'Presidential Communications Operations Office (PCOO)',
    username: 'pcoogov',
  },
  { label: 'Department of Health (DOH)', username: 'DOHgovph' },
  { label: 'Department of Justice (DOJ)', username: 'DOJPH' },
  { label: 'Department of Finance (DOF)', username: 'DOF_PH' },
  { label: 'DFA Philippines', username: 'DFAPHL' },
  { label: 'DILG Philippines', username: 'DILGPhilippines' },
  { label: 'DTI Philippines', username: 'DtiPhilippines' },
  { label: 'DND Philippines', username: 'dndphl' },
  { label: 'DPWHph', username: 'DPWHph' },
  { label: 'DepEd', username: 'DepEd_PH' },
  { label: 'DENR', username: 'DENROfficial' },
  { label: 'Philippine National Police (PNP)', username: 'pnppio' },
  { label: 'PAGASA-DOST', username: 'dost_pagasa' },
  { label: 'COMELEC', username: 'COMELEC' },
  { label: 'Commission on Higher Education (CHED)', username: 'PhCHED' },
  { label: 'Civil Defense PH', username: 'civildefensePH' },
  {
    label: 'Philippine Supreme Court Public Information Office',
    username: 'SCPh_PIO',
  },
];

export default accountSources;
