CREATE TABLE collection_articles (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    published_at text,
    source_name text,
    title text NOT NULL,
    url text,
    url_to_img text,
    collection_id int NOT NULL REFERENCES collections (id) ON DELETE CASCADE
);

CREATE INDEX ON collection_articles (collection_id);

