CREATE TABLE twitter_recent_search_cache (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tweet_id text,
    author_id text,
    created_at text,
    "text" text,
    name text,
    profile_image_url text,
    username text,
    verified boolean,
    twitter_recent_search_request_id int NOT NULL REFERENCES twitter_recent_search_requests (id) ON DELETE CASCADE
);

CREATE INDEX ON twitter_recent_search_cache (twitter_recent_search_request_id);

