CREATE TABLE collection_vera_files (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author text NOT NULL,
    category text NOT NULL,
    "date" text NOT NULL,
    dateText text NOT NULL,
    description text NOT NULL,
    imageStyle text NOT NULL,
    imageUrl text NOT NULL,
    url text NOT NULL,
    title text NOT NULL,
    collection_id int NOT NULL REFERENCES collections (id) ON DELETE CASCADE
);

CREATE INDEX ON collection_vera_files (collection_id);

