CREATE TABLE collection_tweets (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tweet_id text NOT NULL,
    collection_id int NOT NULL REFERENCES collections (id) ON DELETE CASCADE
);

CREATE INDEX ON collection_tweets (collection_id);

