CREATE TABLE collection_tweet_photos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_key text,
    type text,
    url text,
    collection_tweet_id int NOT NULL REFERENCES collection_tweets (id) ON DELETE CASCADE
);

CREATE INDEX ON collection_tweet_photos (collection_tweet_id);

