CREATE table twitter_accounts (
  account_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
  account_name TEXT UNIQUE NOT NULL,
  account_username TEXT UNIQUE NOT NULL
);

INSERT INTO twitter_accounts (account_name, account_username) VALUES
('Presidential Communications Operations Office', 'pcoogov'),
('DILG Philippines', 'DILGPhilippines'),
('DTI Philippines', 'DtiPhilippines'),
('PAGASA-DOST', 'dost_pagasa'),
('DepEd', 'DepEd_PH'),
('Department of Justice (DOJ)', 'DOJPH'),
('DND Philippines', 'dndphl'),
('Department of Finance', 'DOF_PH'),
('Philippine National Police', 'pnppio'),
('Department of Health', 'DOHgovph'),
('DPWHph', 'DPWHph'),
('DENR', 'DENROfficial'),
('DFA Philippines', 'DFAPHL'),
('Philippine Supreme Court Public Information Office', 'SCPh_PIO'),
('Commission on Higher Education (CHED)', 'PhCHED'),
('Civil Defense PH', 'civildefensePH'),
('Senate of the Philippines', 'senatePH'),
('House of Representatives of the Philippines', 'HouseofRepsPH'),
('COMELEC', 'COMELEC'),
('CNN Philippines', 'cnnphilippines'),
('Inquirer', 'inquirerdotnet'),
('Rappler', 'rapplerdotcom'),
('ABS-CBN News', 'ABSCBNNews'),
('GMA News', 'gmanews'),
('Manila Bulettin News', 'manilabulletin'),
('Phil News Agency', 'pnagovph');
