CREATE TABLE twitter_recent_search_cache_photos (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_key text,
    type text,
    url text,
    twitter_recent_search_cache_id int NOT NULL REFERENCES twitter_recent_search_cache (id) ON DELETE CASCADE
);

CREATE INDEX ON twitter_recent_search_cache_photos (twitter_recent_search_cache_id);

