CREATE table twitter_local_sources (
  account_id INT GENERATED BY DEFAULT AS IDENTITY primary key,
  account_name TEXT UNIQUE NOT NULL,
  account_username TEXT UNIQUE NOT NULL
);

INSERT INTO twitter_local_sources (account_name, account_username) VALUES
('Aksyon Radyo Iloilo', 'AksyonRadyo720'),
('RMN Iloilo', 'RMNIloilo774'),
('Daily Guardian', 'dailyguardianph'),
('Panay News', 'panaynewsdotnet');
