CREATE TABLE collection_google_fact_check (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "text" text NOT NULL,
    claimant text NOT NULL,
    claimdDate text NOT NULL,
    publisherName text NOT NULL,
    publisherSite text NOT NULL,
    url text NOT NULL,
    title text NOT NULL,
    reviewDate text NOT NULL,
    textualRating text NOT NULL,
    languageCode text NOT NULL,
    collection_id int NOT NULL REFERENCES collections (id) ON DELETE CASCADE
);

CREATE INDEX ON collection_google_fact_check (collection_id);

